apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: att5-may12-1
  janus-idp.io/tekton: att5-may12-1
  backstage.io/kubernetes-id: att5-may12-1
  backstage.io/kubernetes-namespace: att5-may12-1
  app.kubernetes.io/part-of: att5-may12-1
resources:
  - application-dev.yaml